const Auth0Signin = require('./controllers/auth_0_signin');
const VisitVenue = require('./controllers/visit_venue_controller');
const DeleteVisit = require('./controllers/delete_visit_controller');
const HowManyVisitVenues = require('./controllers/how_many_visiting_controller');
const YelpSearch = require('./controllers/yelp_controller');
const config = require('./config');
const jwt = require('jwt-simple');


const passportService = require('./services/passport');//necessary for passport to work
const passport = require('passport');

const requireAuth = passport.authenticate('jwt',{session:false});

function tokenForUser(user){
  const timestamp = new Date().getTime();

  return jwt.encode({sub:user.id,iat:timestamp},config.secret);
  //user.id is a proxy for user._id which is generated by mongo
//secret is combined with sub & iat to create token
}


module.exports = function(app){

  app.post('/auth/signin',Auth0Signin);
  app.post('/visitvenue',requireAuth,VisitVenue);
  app.put('/deleteattendance',requireAuth,DeleteVisit);
  app.get('/visitvenue/array',HowManyVisitVenues);
  app.get('/yelp/:location',YelpSearch);


}
